spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simplerewards?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: simplerewards_user
    password: "Password123£"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   # create / create-drop / update / validate / none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080

app:
  jwt:
    issuer: simplerewards
    ttlMinutes: 1440
    secret: nq9I+nbiDC40djbSH/KAc985EHdOnfVOEAZNb3GfK5A=